# Generated by Django 6.0.5 on 2026-05-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Passowrd', models.CharField(max_length=100)),
            ],
        ),
    ]
