# Generated by Django 6.0.5 on 2026-05-10 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField()),
                ('DatePosted', models.DateField()),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
    ]
